
language: java

jdk:
  - oraclejdk8

script:
 - mvn clean
 - mvn cobertura:cobertura
 - mvn verify
 - if [ "$TRAVIS_BRANCH" = "master" ]; then mvn versioneye:update; fi


after_success:
  - bash <(curl -s https://codecov.io/bash)
